/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_projectse;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;

/**
 *
 * @author asus
 */
public class loginDesign extends javax.swing.JFrame {

    /**
     * Creates new form loginDesign
     */
    public loginDesign() {
        initComponents();
        
        //Center the design
        this.setLocationRelativeTo(null);
        
        //Creating a border through the LoginTitle
        Border loginTitle_Border=BorderFactory.createMatteBorder(2,2,2,2, Color.blue);
        jPanel1.setBorder(loginTitle_Border);
        
        //set the border to the loginTitle
        loginTitle.setBorder(loginTitle_Border);
        
        //create globle border to the frame
        Border globel_border=BorderFactory.createMatteBorder(3,3,3,3, Color.blue);
        
        
        
        //creating a black border to minimize and close jlables
       // Border label_border=BorderFactory.createMatteBorder(1,1,1,1, Color.black);
        
        //set to the minimize label
       // jLabel_minimize.setBorder(label_border);
        
        //set to the close lable
       // jLabel_close.setBorder(label_border);
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_user = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        loginTitle = new javax.swing.JLabel();
        jButton_close = new javax.swing.JButton();
        jButton_minimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel_password.setBackground(new java.awt.Color(255, 255, 204));
        jLabel_password.setToolTipText("");
        jLabel_password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_password.setOpaque(true);

        jLabel_user.setBackground(new java.awt.Color(255, 255, 204));
        jLabel_user.setToolTipText("");
        jLabel_user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel_user.setOpaque(true);

        jTextField_username.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_username.setText("UserName");
        jTextField_username.setToolTipText("User Name");
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField.setText("password");
        jPasswordField.setToolTipText("Password");
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });

        jButton_login.setBackground(new java.awt.Color(51, 153, 255));
        jButton_login.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(255, 255, 204));
        jButton_login.setText("Login");
        jButton_login.setToolTipText("Login button");
        jButton_login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_user, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addComponent(jPasswordField)
                    .addComponent(jTextField_username))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_user, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addGap(38, 38, 38)
                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        //set icon to Jlabel_password
        jLabel_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pword.png")));
        //set icon to Jlabel_user
        jLabel_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uname.png")));

        loginTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        loginTitle.setForeground(new java.awt.Color(0, 0, 102));
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("Login");
        loginTitle.setToolTipText("Login menu");
        loginTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        loginTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton_close.setBackground(new java.awt.Color(255, 255, 204));
        jButton_close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_close.setForeground(new java.awt.Color(255, 0, 51));
        jButton_close.setText("X");
        jButton_close.setToolTipText("Close(Alt+F4)");
        jButton_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_closeMouseClicked(evt);
            }
        });

        jButton_minimize.setBackground(new java.awt.Color(255, 255, 204));
        jButton_minimize.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton_minimize.setText("-");
        jButton_minimize.setToolTipText("Minimize");
        jButton_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizeMouseClicked(evt);
            }
        });
        jButton_minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimizeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("Resource Management System");

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Admin");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)))
                .addComponent(jButton_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_close, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_minimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizeMouseClicked
       //when click minimized button
       this.setState(JFrame.ICONIFIED);
       
    }//GEN-LAST:event_jButton_minimizeMouseClicked

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        //clear the text field
        if(jTextField_username.getText().trim().toLowerCase().equals("username")||
           jTextField_username.getText().trim().toLowerCase().equals("please enter username!")){
            jTextField_username.setText("");
            jTextField_username.setForeground(Color.black);
        }
        
        //set blue border to the text panel
         Border jTextField_border=BorderFactory.createMatteBorder(1,1,1,1, Color.blue);
       jTextField_username.setBorder(jTextField_border);
       jLabel_user.setBorder(jTextField_border);
       //setBorder
       //set border
      // Border userNameGain_border=BorderFactory.createBevelBorder(8, Color.lightGray, Color.red);
      // jLabel_password.setBorder(userNameGain_border);
       
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
        //if the user name equals to user name or "" empty 
        //we will show it
        if(jTextField_username.getText().trim().equals("") ||
           jTextField_username.getText().trim().toLowerCase().equals("username")){
            
                jTextField_username.setText("   please enter username!");
                jTextField_username.setForeground(Color.red);
                Border jTextBorder_username=BorderFactory.createMatteBorder(3,3,3,3, Color.red);
                jTextField_username.setBorder(jTextBorder_username);
        }
        jLabel_user.setBorder(null);
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
       //Clear the password field if the string is password
       
       //get the password text
       String pass=String.valueOf(jPasswordField.getPassword());
       
       if(pass.trim().toLowerCase().equals("password")||pass.trim().toLowerCase().equals("please enter correct password!")){
           jPasswordField.setText("");
           jPasswordField.setForeground(Color.black);
       }
       //set blue border to the text panel
            Border jTextField_border=BorderFactory.createMatteBorder(1,1,1,1, Color.blue);
       jPasswordField.setBorder(jTextField_border);
       jLabel_user.setBorder(jTextField_border);
       
      
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
         //get the password text
       String pass=String.valueOf(jPasswordField.getPassword());
       
       //checking do user input data or not
         if(pass.trim().toLowerCase().equals("password")|| pass.trim().equals("")){
             jPasswordField.setText("   please enter correct password!");
                jPasswordField.setForeground(Color.red);
                Border jPassBorder_username=BorderFactory.createMatteBorder(3,3,3,3, Color.red);
                jPasswordField.setBorder(jPassBorder_username);
             
         }      
         jLabel_password.setBorder(null);
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void jButton_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_closeMouseClicked
        //if we press the close button
        System.exit(0);
        
    }//GEN-LAST:event_jButton_closeMouseClicked

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        
        PreparedStatement st;
        ResultSet rs;
        
        //get username and password
        String username=jTextField_username.getText().trim();
        String password=String.valueOf(jPasswordField.getPassword());
        
        //creating SELECT query foe the database checking
        String querry="SELECT * FROM AdminTable WHERE name=? AND pass=?";
        
        try {
            st=My_conn.getConnection().prepareStatement(querry);
            
            st.setString(1,username);
            st.setString(2,password);
            
            rs=st.executeQuery();
            
            if(rs.next()){
                //show a new form
                Menue01 form=new Menue01();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                
                //close the current form
                this.dispose();
                
                
                
            }else{
               //error message 
               JOptionPane.showMessageDialog(null,"Invalid username/password","Login Error",2);
               
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(loginDesign.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton_minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimizeActionPerformed
       this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton_minimizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_close;
    private javax.swing.JButton jButton_login;
    private javax.swing.JButton jButton_minimize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JLabel loginTitle;
    // End of variables declaration//GEN-END:variables
}
