/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_projectse;

import javax.swing.JFrame;
import java.sql.*;

/**
 *
 * @author asus
 */
public class Menue01 extends javax.swing.JFrame {

    /**
     * Creates new form Menue01
     */
    public Menue01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        storage = new javax.swing.JButton();
        chemicalStock = new javax.swing.JButton();
        employers = new javax.swing.JButton();
        settings = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        storage.setText("Storage");
        storage.setActionCommand("jButton_1");
        storage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        storage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        storage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageActionPerformed(evt);
            }
        });
        jPanel1.add(storage);
        storage.setBounds(300, 80, 110, 90);

        chemicalStock.setText("ChemicalStock");
        chemicalStock.setActionCommand("jButton_1");
        chemicalStock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chemicalStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chemicalStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chemicalStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemicalStockActionPerformed(evt);
            }
        });
        jPanel1.add(chemicalStock);
        chemicalStock.setBounds(90, 80, 110, 90);

        employers.setText("Employers");
        employers.setActionCommand("jButton_1");
        employers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        employers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        employers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employersActionPerformed(evt);
            }
        });
        jPanel1.add(employers);
        employers.setBounds(490, 80, 110, 90);

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings_logo.png"))); // NOI18N
        settings.setText("Settings");
        settings.setToolTipText("Create new admin/employer accounts , feedbacks  and etc.");
        settings.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });
        jPanel1.add(settings);
        settings.setBounds(550, 391, 170, 90);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CloseLogo.png"))); // NOI18N
        jButton4.setText("jButton4");
        jButton4.setToolTipText("Close Window");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(690, 0, 70, 66);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        jButton5.setText("jButton5");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(630, 0, 60, 68);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kalutara.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chemicalStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemicalStockActionPerformed
            chemicalStock form=new chemicalStock();
            form.setVisible(true);
            form.pack();
            form.setLocationRelativeTo(null);
            
            //close curent window
                this.dispose();
    }//GEN-LAST:event_chemicalStockActionPerformed

    private void storageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageActionPerformed
        storage form=new storage();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        
        //close current window
            this.dispose();
        
    }//GEN-LAST:event_storageActionPerformed

    private void employersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employersActionPerformed
        employers form=new employers();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        
        //close current window
            this.dispose();
            
    }//GEN-LAST:event_employersActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        settingsLogin form=new settingsLogin();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        
        //close current window
            this.dispose();
    }//GEN-LAST:event_settingsActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menue01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menue01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menue01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menue01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menue01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chemicalStock;
    private javax.swing.JButton employers;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton settings;
    private javax.swing.JButton storage;
    // End of variables declaration//GEN-END:variables
}
