/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_projectse;


import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;

public class Registry_form extends javax.swing.JFrame {

    /**
     * Creates new form Registry_form
     */
    public Registry_form() {
        initComponents();
        //center
    this.setLocationRelativeTo(null);
    //Creating a border through the LoginTitle
        Border loginTitle_Border=BorderFactory.createMatteBorder(2,2,2,2, Color.blue);
        jPanel2.setBorder(loginTitle_Border);
        
        //set the border to the loginTitle
        regTitle.setBorder(loginTitle_Border);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_minimize = new javax.swing.JButton();
        jButton_close = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButton_reg = new javax.swing.JButton();
        jTextField_nic = new javax.swing.JTextField();
        jTextField_email = new javax.swing.JTextField();
        jPasswordFieldconfirmation = new javax.swing.JPasswordField();
        jButton_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);

        regTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        regTitle.setForeground(new java.awt.Color(0, 0, 102));
        regTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regTitle.setText("Register Portal");
        regTitle.setToolTipText("register here");
        regTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        regTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setText("Resource Management System");

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Admin");
        jLabel2.setToolTipText("");

        jButton_minimize.setBackground(new java.awt.Color(255, 255, 204));
        jButton_minimize.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton_minimize.setText("-");
        jButton_minimize.setToolTipText("Minimize");
        jButton_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizeMouseClicked(evt);
            }
        });

        jButton_close.setBackground(new java.awt.Color(255, 255, 204));
        jButton_close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_close.setForeground(new java.awt.Color(255, 0, 51));
        jButton_close.setText("X");
        jButton_close.setToolTipText("Close(Alt+F4)");
        jButton_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_closeMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jTextField_username.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_username.setText("UserName");
        jTextField_username.setToolTipText("User Name");
        jTextField_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });

        jPasswordField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField.setText("password");
        jPasswordField.setToolTipText("Password");
        jPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });

        jButton_reg.setBackground(java.awt.Color.blue);
        jButton_reg.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton_reg.setForeground(new java.awt.Color(255, 255, 204));
        jButton_reg.setText("Register");
        jButton_reg.setToolTipText("Register");
        jButton_reg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_reg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_regMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_regMouseExited(evt);
            }
        });
        jButton_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_regActionPerformed(evt);
            }
        });

        jTextField_nic.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_nic.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_nic.setText("National Identification Card (NIC)");
        jTextField_nic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField_nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_nicFocusLost(evt);
            }
        });

        jTextField_email.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_email.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_email.setText("EmailAddress");
        jTextField_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusLost(evt);
            }
        });

        jPasswordFieldconfirmation.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPasswordFieldconfirmation.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordFieldconfirmation.setText("password");
        jPasswordFieldconfirmation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPasswordFieldconfirmation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldconfirmationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldconfirmationFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_nic)
                                .addComponent(jTextField_username)
                                .addComponent(jTextField_email, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
                            .addComponent(jPasswordFieldconfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTextField_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPasswordFieldconfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jButton_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back-512.png"))); // NOI18N
        jButton_Back.setToolTipText("Back to Main Menue");
        jButton_Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(regTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_close, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_close, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_minimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(regTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizeMouseClicked
        //when click minimized button
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jButton_minimizeMouseClicked

    private void jButton_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_closeMouseClicked
        //if we press the close button
        System.exit(0);

    }//GEN-LAST:event_jButton_closeMouseClicked

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        //clear the text field
        if(jTextField_username.getText().trim().toLowerCase().equals("username")||
            jTextField_username.getText().trim().toLowerCase().equals("please enter username!")){
            jTextField_username.setText("");
            jTextField_username.setForeground(Color.black);
        }

        //set blue border to the text panel
//        Border jTextField_border=BorderFactory.createMatteBorder(1,1,1,1, Color.blue);
//        jTextField_username.setBorder(jTextField_border);
//        jLabel_user.setBorder(jTextField_border);
        //setBorder
        //set border
        // Border userNameGain_border=BorderFactory.createBevelBorder(8, Color.lightGray, Color.red);
        // jLabel_password.setBorder(userNameGain_border);

    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
        //if the user name equals to user name or "" empty
        //we will show it
        if(jTextField_username.getText().trim().equals("") ||
            jTextField_username.getText().trim().toLowerCase().equals("username")){

            jTextField_username.setText("   please enter username!");
            jTextField_username.setForeground(Color.red);
            Border jTextBorder_username=BorderFactory.createMatteBorder(3,3,3,3, Color.red);
            jTextField_username.setBorder(jTextBorder_username);
        }
        //jLabel_user.setBorder(null);
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        //Clear the password field if the string is password

        //get the password text
        String pass=String.valueOf(jPasswordField.getPassword());

        if(pass.trim().toLowerCase().equals("password")||pass.trim().toLowerCase().equals("please enter correct password!")){
            jPasswordField.setText("");
            jPasswordField.setForeground(Color.black);
        }
        //set blue border to the text panel
//        Border jTextField_border=BorderFactory.createMatteBorder(1,1,1,1, Color.blue);
//        jPasswordField.setBorder(jTextField_border);
//        jLabel_user.setBorder(jTextField_border);

    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
        //get the password text
        String pass=String.valueOf(jPasswordField.getPassword());

        //checking do user input data or not
        if(pass.trim().toLowerCase().equals("password")|| pass.trim().equals("")){
            jPasswordField.setText("   please enter correct password!");
            jPasswordField.setForeground(Color.red);
            Border jPassBorder_username=BorderFactory.createMatteBorder(3,3,3,3, Color.red);
            jPasswordField.setBorder(jPassBorder_username);

        }
     //   jLabel_password.setBorder(null);
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void jButton_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_regActionPerformed
            
        String username=jTextField_username.getText();
        String email=jTextField_email.getText();
        String nic=jTextField_nic.getText();
        String pass1=String.valueOf(jPasswordField.getPassword());
        String pass2 =String.valueOf(jPasswordFieldconfirmation.getPassword());
        
        if(confirmation()){
            if(!checkNIC(nic)){
                PreparedStatement ps;
                ResultSet rs;
                String RegisterUserQuery="INSERT INTO `admintable`(`name`,`pass`,`email`,`nic`) VALUES (?,?,?,?)";
                
                try {
                    ps=My_conn.getConnection().prepareStatement(RegisterUserQuery);
                    ps.setString(1,username);
                    ps.setString(2,pass1);
                    ps.setString(3,email);
                    ps.setString(4,nic);
                    
                    if(ps.executeUpdate() != 0){
                        JOptionPane.showMessageDialog(null,"Your Account Has Been Created!");
                    }else{
                        JOptionPane.showMessageDialog(null,"Error:Check Your Connection");
                    }
                    
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Registry_form.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        }
        
        
        
    }//GEN-LAST:event_jButton_regActionPerformed

    private void jButton_regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_regMouseEntered
        jButton_reg.setBackground(Color.red);
    }//GEN-LAST:event_jButton_regMouseEntered

    private void jButton_regMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_regMouseExited
        jButton_reg.setBackground( Color.blue);
    }//GEN-LAST:event_jButton_regMouseExited

    private void jTextField_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusGained
        // TODO add your handling code here://clear the text field
        if(jTextField_email.getText().trim().toLowerCase().equals("emailaddress")||
            jTextField_email.getText().trim().toLowerCase().equals("please enter emailaddress!")){
            jTextField_email.setText("");
            jTextField_email.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_emailFocusGained

    private void jTextField_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusLost
          //if the user name equals to user name or "" empty
        //we will show it
        if(jTextField_email.getText().trim().equals("") ||
            jTextField_email.getText().trim().toLowerCase().equals("emailaddress")){

            jTextField_email.setText("   please enter EmailAddress!");
            jTextField_email.setForeground(Color.red);
            Border jTextBorder_username=BorderFactory.createMatteBorder(3,3,3,3, Color.red);
            jTextField_email.setBorder(jTextBorder_username);
        }
    }//GEN-LAST:event_jTextField_emailFocusLost

    private void jTextField_nicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nicFocusGained
         if(jTextField_nic.getText().trim().toLowerCase().equals("national identification card (nic)")||
            jTextField_nic.getText().trim().toLowerCase().equals("please enter nic!")){
            jTextField_nic.setText("");
            jTextField_nic.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_nicFocusGained

    private void jTextField_nicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nicFocusLost
         //if the user name equals to user name or "" empty
        //we will show it
        if(jTextField_nic.getText().trim().equals("") ||
            jTextField_nic.getText().trim().toLowerCase().equals("emailaddress")){

            jTextField_nic.setText("   please enter EmailAddress!");
            jTextField_nic.setForeground(Color.red);
            Border jTextBorder_username=BorderFactory.createMatteBorder(3,3,3,3, Color.red);
            jTextField_nic.setBorder(jTextBorder_username);
        }
    }//GEN-LAST:event_jTextField_nicFocusLost

    private void jPasswordFieldconfirmationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldconfirmationFocusGained
         //Clear the password field if the string is password

        //get the password text
        String passcheck=String.valueOf(jPasswordFieldconfirmation.getPassword());

        if(passcheck.trim().toLowerCase().equals("password")||passcheck.trim().toLowerCase().equals("please confirm the password!")){
            jPasswordFieldconfirmation.setText("");
            jPasswordFieldconfirmation.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordFieldconfirmationFocusGained

    private void jPasswordFieldconfirmationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldconfirmationFocusLost
         //get the password text
        String pass=String.valueOf(jPasswordFieldconfirmation.getPassword());

        //checking do user input data or not
        if(pass.trim().toLowerCase().equals("password")|| pass.trim().equals("")){
            jPasswordFieldconfirmation.setText("   please confirm the password!");
            jPasswordFieldconfirmation.setForeground(Color.red);
            Border jPassBorder_username=BorderFactory.createMatteBorder(3,3,3,3, Color.red);
            jPasswordFieldconfirmation.setBorder(jPassBorder_username);

        }
    }//GEN-LAST:event_jPasswordFieldconfirmationFocusLost

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        AddNewAdmin form=new AddNewAdmin();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);

        //current window close
        this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    //creating function for check password confirmations
    public boolean confirmation(){
       String pass1=String.valueOf(jPasswordField.getPassword());
       String pass2=String.valueOf(jPasswordFieldconfirmation.getPassword());
       
       if(pass1.equals(pass2)){
           return true;
       }else{
        
        return false;
        
       }
        
    }
    
    //creating function for check NIC is existing or not 
    public boolean checkNIC(String nic){
      
        
        PreparedStatement st;
        ResultSet rs;
      
        boolean nic_exist=false;
        String querry ="SELECT * FROM WHERE nic=?";
        try {
            st=My_conn.getConnection().prepareStatement(querry);
            st.setString(1,nic);
            rs=st.executeQuery(querry);
            
            if(rs.next()){
                nic_exist=true;
                JOptionPane.showMessageDialog(null,"This ID has been saved ","NIC is not valied",2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registry_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        return nic_exist;
        
    }
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registry_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registry_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registry_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registry_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registry_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_close;
    private javax.swing.JButton jButton_minimize;
    private javax.swing.JButton jButton_reg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldconfirmation;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_nic;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JLabel regTitle;
    // End of variables declaration//GEN-END:variables
}
